#! /usr/bin/env bash


# This creates a HTTP server sharing the contents of the current folder.
# The server is served at the local ip, port 9000
server() {
    py python -m http.server 9000
}


# This creates a FTP server sharing the contents of the current folder.
# The server is served at the local ip, port 2121, under annonymous login.
serverf() {
    py --with pyftpdlib python -m pyftpdlib
}
